### ISSUE TITLE
Filament issue machine error octoprint 1.8.7

### ISSUE THREAD

**Issue by omgitsmatt** [ssorgatem/Octoprint-Filament-Reloaded#23]
hi i had a problem with this, octoprint 1.8.7 python 3.9.2 octoPi 1.0.0
I installed it and set the sensor to 1 because it was on -1 and just when the filament was out of the sensor the machine return to the start point and give me error. Can you help me please? I also give you a log file
@nickmitchko
[octoprint filament log.log](https://github.com/user-attachments/files/17571939/octoprint.filament.log.log)

**Comment by nickmitchko** [comment]
Hello @omgitsmatt,

Can you take a screenshot of your settings in the octoprint UI?

There's a few possibilities here:
1. Somehow the setting for the pin-mode got dropped
2. The pin you are using is not gpio compatible or the pin is used by another plugin
3. The limit switch is wired incorrectly

Some relevant things from your logs -- see last line about pinmode being missing...
```
2024-10-30 08:57:32,990 - octoprint.plugins.filamentreload - INFO - Pin not configured, won't work unless configured!
2024-10-30 08:58:39,989 - octoprint.plugins.filamentreload - INFO - Pin not configured, won't work unless configured!
2024-10-30 09:01:43,396 - octoprint.plugin - ERROR - Error while calling plugin filamentreload
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/plugin/__init__.py", line 273, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_filamentreload/__init__.py", line 201, in on_event
    if event is Events.PRINT_STARTED and self.no_filament() and self.prevent_print:
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_filamentreload/__init__.py", line 178, in no_filament
    nofilament = GPIO.input(self.pin) != self.switch
RuntimeError: Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)
```

**Comment by omgitsmatt** [comment]
hi @nickmitchko thank you for the tempestive answer, i send you the scrrenshot of octoprint settings ui 
![plugin](https://github.com/user-attachments/assets/8bf6aaad-f6d9-4433-b1ad-bf2573cb0a19)

**Comment by omgitsmatt** [comment]
@nickmitchko the pin was on -1 before the print and i set it to 1

**Comment by omgitsmatt** [comment]
@nickmitchko

**Comment by nickmitchko** [comment]
Can you take a screenshot of the settings pane, something simple is off.

**Comment by omgitsmatt** [comment]
@nickmitchko what settings pane? what section? i send you this screen that are the settings of the plugin
![Cattura](https://github.com/user-attachments/assets/5ab5616c-bf32-4625-9088-fa310ca62181)

**Comment by omgitsmatt** [comment]
@nickmitchko

**Comment by nickmitchko** [comment]
Hey @omgitsmatt, The error is you are receiving is that your pin sensor is reading from the wrong pin. The pin number should be the physical board pin here: [https://pinout.xyz/](https://pinout.xyz/)

Since you have `1` as the PIN number, when the filament is out it is shorting the power pin (3v3) 
![Image](https://github.com/user-attachments/assets/59031ed2-19bd-4f67-a01c-a43f3f590c5a)

The pin you use should be connected to another pin, and personally I put the reader pin here:

![Image](https://github.com/user-attachments/assets/5d0a4183-9599-4237-9e85-feb243b4cb23)

**Comment by nickmitchko** [comment]
@omgitsmatt make sure when you check the settings that you test the pin (should show in the top of the status bar) with the filament available and out by putting a small piece of filament through your sensor

**Comment by omgitsmatt** [comment]
![Image](https://github.com/user-attachments/assets/55668883-bd69-4d3e-84aa-9611fd98c4f0) Hi Nick i changed the pin to 18 and now the filament icon (i guess this is the filament icon) is orange but if i put the filament in the sensor it doesn't change, is always orange. I tried also to put the pin another time to 1 only to see if was orange because of the right pin but it's always orange now, also with the pin 1, before it ever wasn't orange

**Comment by omgitsmatt** [comment]
@nickmitchko how can i know the right pin?

**Comment by omgitsmatt** [comment]
@nickmitchko

**Comment by nickmitchko** [comment]
The right pin is the pin where you plug your sensor in your GPIO pin array on the RPI
